feat(update-index): automate adding release notes to index
grafana/grafana-github-actions pull request #54
Opened 2021-12-16 11:14 UTC by tolzhabayev

**Why?**
Currently, we have to update `_index.md` file manually when creating a changelog file. This PR automates it.

**Additional changes**
- Remove `nock` as it is not really used anymore
- Make unit tests run silently per default

Fixes: #13

2021-12-16 11:19 UTC, hugohaggmark reviewed
What happens if we run UpdateChangelog action for a previous release, let's say 8.3.0. Will this still work? I think we should add that as a test case either way.

2021-12-16 11:20 UTC, tolzhabayev commented
> What happens if we run UpdateChangelog action for a previous release, let's say 8.3.0. Will this still work? I think we should add that as a test case either way.

good point, I will look into making it not "forward-only".

2021-12-16 11:24 UTC, marefr commented
I was under the impression that this has been sort of supported earlier, but I might be confused/remember incorrectly. I'll have a look at the changes :+1:

2021-12-16 16:12 UTC, marefr requested changes
See comment

2021-12-16 16:12 UTC, marefr commented on update-changelog/testdata/_index.md
> +- [Release notes for 8.3.0]({{< relref "release-notes-8-3-0" >}})
Based on earlier comment in PR. With this update adding a test for generating changelog for 8.2.2 would be nice and it should be inserted between 8.3.0 and 8.2.1 :) Maybe can make use of markers as we do with the changelog.md file, i.e. `<!-- 8.3.3 START -->` and `<!-- 8.3.3 END -->` etc, so you don't have to parse the markdown. 

```suggestion
- [Release notes for 8.3.2]({{< relref "release-notes-8-3-2" >}})
- [Release notes for 8.3.1]({{< relref "release-notes-8-3-1" >}})
- [Release notes for 8.3.0]({{< relref "release-notes-8-3-0" >}})
- [Release notes for 8.2.1]({{< relref "release-notes-8-2-1" >}})
- [Release notes for 8.2.0]({{< relref "release-notes-8-2-0" >}})
```

2021-12-21 14:47 UTC, tolzhabayev commented
@marefr @hugohaggmark please re-review, it should now add it into the proper position for any version.

2021-12-21 15:00 UTC, marefr approved these changes
Great LGTM

2021-12-22 05:21 UTC, hugohaggmark approved these changes
Great work on this, so awesome that you added all those tests 🎉

2021-12-22 09:04 UTC, merged